---@class AE_Global
---@field weeklyReset number
---@field characters AE_Character[]
---@field minimap { minimapPos: number, hide: boolean, lock: boolean }
---@field sorting AE_CharacterSortingOption
---@field showTiers boolean
---@field showScores boolean
---@field showAffixColors boolean
---@field showAffixHeader boolean
---@field showZeroRatedCharacters boolean
---@field showRealms boolean
---@field showGuildInformation boolean
---@field currentCharacterMarker AE_CurrentCharacterMarkerId
---@field announceKeystones { autoParty: boolean, multiline: boolean, multilineNames: boolean}
---@field announceResets boolean
---@field vault { raids: boolean, dungeons: boolean, world: boolean }
---@field prey { enabled: boolean, hiddenDifficulties: table<number, boolean> }
---@field raids { enabled: boolean, colors: boolean, currentTierOnly: boolean, hiddenDifficulties: table<number, boolean>, killIcon: string, modifiedInstanceOnly: boolean }
---@field dungeons { enabled: boolean }
---@field world { enabled: boolean }
---@field currencies { enabled: boolean, hiddenCurrencies: table<number, boolean>, showIcons: boolean, showMaxEarned: boolean, alignCenter: boolean }
---@field interface { windowScale: number, windowColor: ColorTable}
---@field liqui LiqUI_DB
---@field useRIOScoreColor boolean

---@class AE_Data
---@field db { global: AE_Global }|nil
---@field dbVersion number
---@field defaultDB table
---@field defaultCharacter AE_Character
---@field affixes table
---@field vaultTypes table
---@field mythicPlusVaultItemLevels table<number, table<number, number>>
---@field affixRotations table
---@field keystones table
---@field currencies AE_Currency[]
---@field preyAffixes AE_PreyAffix[]
---@field preyDifficulties AE_PreyDifficulty[]
---@field preyQuests AE_PreyQuest[]
---@field cache AE_Cache

---@class AE_Cache
---@field currentAffixes MythicPlusKeystoneAffix[]
---@field pendingKeystoneAnnounce boolean?
